kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: APP
    required: true
    value: haahka
  - name: BRANCH
    required: true
  - name: GIT_HOST
    required: true
    value: https://github.com
  - name: ORG
    required: true
    value: luomus
  - name: TAG
    required: true
    value: latest
  - name: STORAGE
    required: true
    value: "20Gi"
  - name: CRON
    required: true
    value: job
  - name: CRON_SCHEDULE
    required: true
    value: "0 20 * * *"
  - name: CRON_CMD
    required: true
    value: '["Rscript", "--vanilla", "update.R"]'
  - name: CRON_LIMIT
    required: true
    value: "7"
  - name: CRON_CONCURRENCY
    required: true
    value: "Forbid"
  - name: PATH
    required: true
    value: /home/user/data
  - name: FINBIF_ACCESS_TOKEN
    required: true
  - name: FINBIF_API_URL
    required: true
  - name: FINBIF_EMAIL
    required: true
  - name: FINBIF_WAREHOUSE
    required: true
  - name: APP_PORT
    required: true
    value: "3838"
  - name: HOST
    required: true
  - name: GITHUB_SECRET
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{64}"
metadata:
  name: ${APP}
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP}-${BRANCH}:${TAG}
    source:
      type: Git
      git:
        uri: ${GIT_HOST}/${ORG}/${APP}.git
        ref: ${BRANCH}
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: ${GITHUB_SECRET}
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    lookupPolicy:
      local: true
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    replicas: 1
    selector:
      app: ${APP}
      deploymentconfig: ${APP}-${BRANCH}
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${APP}-${BRANCH}
      spec:
        containers:
        - image: ${APP}-${BRANCH}:${TAG}
          name: ${APP}-${BRANCH}
          volumeMounts:
          - mountPath: ${PATH}
            name: ${APP}-${BRANCH}
          env:
          - name: FINBIF_ACCESS_TOKEN
            value: ${FINBIF_ACCESS_TOKEN}
          - name: FINBIF_API_URL
            value: ${FINBIF_API_URL}
          - name: FINBIF_EMAIL
            value: ${FINBIF_EMAIL}
          - name: FINBIF_WAREHOUSE
            value: ${FINBIF_WAREHOUSE}
          ports:
          - containerPort: ${{APP_PORT}}
        volumes:
        - name: ${APP}-${BRANCH}
          persistentVolumeClaim:
            claimName: ${APP}-${BRANCH}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APP}-${BRANCH}
        from:
          kind: ImageStreamTag
          name: ${APP}-${BRANCH}:${TAG}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
   name: ${APP}-${BRANCH}
  spec:
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    resources:
      requests:
        storage: ${STORAGE}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${APP_PORT}
      port: ${{APP_PORT}}
      targetPort: ${{APP_PORT}}
    selector:
      app: ${APP}
      deploymentconfig: ${APP}-${BRANCH}
- kind: Route
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    host: ${HOST}
    port:
      targetPort: ${{APP_PORT}}
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APP}-${BRANCH}
    wildcardPolicy: None
- kind: CronJob
  apiVersion: batch/v1beta1
  metadata:
    name: ${APP}-${BRANCH}
  spec:
    schedule: ${CRON_SCHEDULE}
    concurrencyPolicy: ${CRON_CONCURRENCY}
    successfulJobsHistoryLimit: ${{CRON_LIMIT}}
    failedJobsHistoryLimit: ${{CRON_LIMIT}}
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              app: ${APP}
          spec:
            containers:
            - name: ${APP}-${BRANCH}-${CRON}
              image: ${APP}-${BRANCH}:${TAG}
              command: ${{CRON_CMD}}
              volumeMounts:
              - mountPath: ${PATH}
                name: ${APP}-${BRANCH}
              env:
              - name: FINBIF_ACCESS_TOKEN
                value: ${FINBIF_ACCESS_TOKEN}
              - name: FINBIF_API_URL
                value: ${FINBIF_API_URL}
              - name: FINBIF_EMAIL
                value: ${FINBIF_EMAIL}
              - name: FINBIF_WAREHOUSE
                value: ${FINBIF_WAREHOUSE}
            volumes:
            - name: ${APP}-${BRANCH}
              persistentVolumeClaim:
                claimName: ${APP}-${BRANCH}
            restartPolicy: Never
